# Generated by Django 3.1.3 on 2020-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
