# Generated by Django 3.1.3 on 2020-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0002_product_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('itemShop', models.CharField(max_length=200)),
                ('itemDate', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'ordering': ['-itemDate'],
            },
        ),
    ]
