# Generated by Django 3.1.3 on 2020-11-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0004_childproduct_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childproduct',
            name='like',
        ),
    ]
