# Generated by Django 3.1.3 on 2020-11-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0005_remove_childproduct_like'),
        ('zebraapp', '0004_tip_tipbody'),
    ]

    operations = [
    ]
