# Generated by Django 3.1.3 on 2020-11-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0008_auto_20201123_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myitem',
            name='itemDate',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
