# Generated by Django 3.1.3 on 2020-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0009_auto_20201123_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
