# Generated by Django 3.1.3 on 2020-11-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0010_likes_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
