# Generated by Django 3.0.6 on 2020-11-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0010_auto_20201130_1441'),
        ('zebraapp', '0011_auto_20201130_1345'),
    ]

    operations = [
    ]
