# Generated by Django 3.1.3 on 2020-11-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0011_auto_20201130_1345'),
        ('zebraapp', '0010_auto_20201130_1441'),
    ]

    operations = [
    ]
