# Generated by Django 3.1.3 on 2020-12-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0012_merge_20201130_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
