# Generated by Django 3.1.3 on 2020-12-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0013_auto_20201202_1634'),
        ('zebraapp', '0012_merge_20201130_1528'),
    ]

    operations = [
    ]
