# Generated by Django 3.1.3 on 2020-12-07 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zebraapp', '0014_merge_20201203_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='myitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_myitem', to='auth.user'),
            preserve_default=False,
        ),
    ]
