# Generated by Django 3.1.3 on 2020-12-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebraapp', '0017_auto_20201207_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myitem',
            name='itemDate',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
